---
- name: restart ssh
  service:
    name: sshd
    state: restarted
  become: true

- name: reload ssh
  service:
    name: sshd
    state: reloaded
  become: true

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
  become: true