- name: Ensure users exist with passwords
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: root
    append: true
    shell: /bin/bash
    create_home: true
  loop: "{{ users }}"

- name: Add SSH public key for each user
  ansible.posix.authorized_key:
      user: "{{ item.name }}"
      key: "{{ my_pubkey }}"
      state: present
  loop: "{{ users }}"
  notify: restart ssh

